// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbsljowmqonyldjaazkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic2xqb3dtcW9ueWxkamFhemtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjQ2ODMsImV4cCI6MjA2ODQwMDY4M30.ARZjongjm_jEIHKc-kR1CyN9EzBY7yp_2IBq4Ado7A4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});